import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Sidebar } from "@/components/sidebar";
import { Providers } from "@/components/providers";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { SheetMenu } from "@/components/sheetmenu";
import { SearchComponent } from "@/components/search";
import { ProfileMenu } from "@/components/profilemenu";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Dashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex min-h-screen w-full flex-col bg-muted/40">
        <Sidebar />
        <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
          <header className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
            <SheetMenu />
            <Breadcrumbs />
            <SearchComponent />
            <ProfileMenu />
          </header>
          <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8 lg:grid-cols-3 xl:grid-cols-3">
            {children}
          </main>
        </div>
      </div>
    </>
  );
}
